//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidPackBackEnd.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadItem
    {
        public int Id { get; set; }
        public int ExistingSession_Id { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
    
        public virtual ExistingSession ExistingSession { get; set; }
    }
}
