//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidPackBackEnd.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VidPackEntities : DbContext
    {
        public VidPackEntities()
            : base("name=VidPackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ExistingSession> ExistingSession { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<DownloadItem> DownloadItem { get; set; }
    }
}
